apps/blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView

from .feeds import BlogPageFeed
from .views import EntryPageServe, EntryPageUpdateCommentsView, PortfolioPage, ContactPage, ContactSuccessPage

urlpatterns = [
    url(
        regex=r'^entry_page/(?P<entry_page_id>\d+)/update_comments/$',
        view=EntryPageUpdateCommentsView.as_view(),
        name='entry_page_update_comments'
    ),
    url(
        regex=r'^(?P<blog_slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        view=EntryPageServe.as_view(),
        name='entry_page_serve_slug'
    ),
    url(
        regex=r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        view=EntryPageServe.as_view(),
        name='entry_page_serve'
    ),
    url(
        regex=r'^(?P<blog_slug>[-\w]+)/feed/$',
        view=BlogPageFeed(),
        name='blog_page_feed_slug'
    ),
    url(
        regex=r'^feed/$',
        view=BlogPageFeed(),
        name='blog_page_feed'
    ),

    url(
        regex=r'^contact/$',
        view=ContactPage.as_view(),
        name='contact_page',
    ),

    url(r'^contact/thanks/$',
        ContactSuccessPage.as_view()
    ),

    url(
        regex=r'^portfolio/$',
        view=PortfolioPage.as_view(),
        name='portfolio_page',
    ),

    url(
        regex=r'^post/$',
        view=TemplateView.as_view(template_name="blog/entry_page.html"),
        name='post_page',
    )
]


# from wagtail.wagtailcore import urls as wagtail_urls
# from wagtail.wagtailadmin import urls as wagtailadmin_urls
# from wagtail.wagtaildocs import urls as wagtaildocs_urls
# from wagtail.wagtailsearch import urls as wagtailsearch_urls
# from wagtail.contrib.wagtailsitemaps.views import sitemap
#
# urlpatterns.extend([
#     url(
#         regex=r'^blog_admin/',
#         view=include(wagtailadmin_urls)
#     ),
#     url(
#         regex=r'',
#         view=include(wagtail_urls)
#     ),
#     url(
#         regex=r'^search/',
#         view=include(wagtailsearch_urls)
#     ),
#     url(
#         regex=r'^documents/',
#         view=include(wagtaildocs_urls)
#     ),
#     url(
#         regex='^sitemap\.xml$',
#         view=sitemap
#     )
#     ])


def get_entry_url(entry, blog_page, root_page):
    """
    Get the entry url given and entry page a blog page instances.
    It will use an url or another depending if blog_page is the root page.
    """
    if root_page == blog_page:
        return reverse('blog:entry_page_serve', kwargs={
            'year': entry.date.strftime('%Y'),
            'month': entry.date.strftime('%m'),
            'day': entry.date.strftime('%d'),
            'slug': entry.slug
        })
    else:
        return reverse('blog:entry_page_serve_slug', kwargs={
            'blog_slug': blog_page.slug,
            'year': entry.date.strftime('%Y'),
            'month': entry.date.strftime('%m'),
            'day': entry.date.strftime('%d'),
            'slug': entry.slug
        })


def get_feeds_url(blog_page, root_page):
    """
    Get the feeds urls a blog page instance.
    It will use an url or another depending if blog_page is the root page.
    """
    if root_page == blog_page:
        return reverse('blog_page_feed')
    else:
        return reverse('blog_page_feed_slug', kwargs={'blog_slug': blog_page.slug})

config/urls.py
# -*- encoding:utf-8 -*-

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from apps.contrib.views import LandingView

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls


urlpatterns = [

    # Django ADMIN
    url(settings.ADMIN_URL, admin.site.urls),

    # Blog Admin
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^offline/$', TemplateView.as_view(template_name='offline.html')),

    # Blog Pages
    url(r'', include('apps.blog.urls', namespace='blog')),
    url(r'', include(wagtail_urls)),

    # Platform VIEWS and ENDPOINTS
    url(r'', include('apps.users.urls', namespace='users')),
    url(r'', include('apps.credentials.urls', namespace="credentials")),

    # Third parts
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^docs/', include('rest_framework_swagger.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:

    urlpatterns += [
        url(
            regex=r'^test/login/?$',
            view=TemplateView.as_view(template_name='test/login.html')
        ),
    ]

    # Test Email templates
    urlpatterns += [
        url(
            regex=r'^email/base/?$',
            view=TemplateView.as_view(template_name='layouts/base_email.html')
        ),

        url(
            regex=r'^email/web/confirmation/?$',
            view=TemplateView.as_view(template_name='account/email/email_confirmation_message.html')
        ),

        url(
            regex=r'^email/web/signup/?$',
            view=TemplateView.as_view(template_name='account/email/email_confirmation_signup_message.html')
        ),

        url(
            regex=r'^email/web/password-reset/?$',
            view=TemplateView.as_view(template_name='account/email/password_reset_key_message.html')
        ),

        url(
            regex=r'^email/mobile/welcome/?$',
            view=TemplateView.as_view(template_name='credentials/email/account_welcome_message.html')
        ),
    ]

    # Test error pages
    urlpatterns += [
        url(r'^400/$', TemplateView.as_view(template_name='errors/400.html')),
        url(r'^403/$', TemplateView.as_view(template_name='errors/403.html')),
        url(r'^404/$', TemplateView.as_view(template_name='errors/404.html')),
        url(r'^500/$', TemplateView.as_view(template_name='errors/500.html')),
    ]

    urlpatterns += [
        url(r'^error/400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^error/403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^error/404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^error/500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
else:
    handler400 = TemplateView.as_view(template_name="errors/400.html")
    handler403 = TemplateView.as_view(template_name="errors/403.html")
    handler404 = TemplateView.as_view(template_name="errors/404.html")
    handler500 = TemplateView.as_view(template_name="errors/500.html")

apps/blog/models.py
# -*- coding: utf-8 -*-
import datetime

from django.conf import settings

from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from modelcluster.contrib.taggit import ClusterTaggableManager
from wagtail.contrib.table_block.blocks import TableBlock
from wagtail.wagtailcore import blocks
from wagtail.wagtailcore.fields import StreamField, RichTextField

from wagtail.wagtailcore.models import Page
from wagtail.wagtailadmin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel, PageChooserPanel, \
    StreamFieldPanel
from wagtail.wagtailimages.blocks import ImageChooserBlock
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel
from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailsearch import index
from taggit.models import TaggedItemBase, Tag as TaggitTag
from modelcluster.fields import ParentalKey

from apps.blog.blocks import CodeBlock, MarkDownBlock, RSTBlock
from .routes import BlogRoutes
from .managers import TagManager, CategoryManager


class BlogPage(BlogRoutes, Page):

    description = models.CharField(
        verbose_name=_('Description'),
        max_length=255,
        blank=True,
        help_text=_("The blog description that will appear under the title."),
    )

    header_image = models.ForeignKey(
        'wagtailimages.Image',
        verbose_name=_('Header image'),
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    display_comments = models.BooleanField(
        default=False,
        verbose_name=_('Display comments'),
    )

    display_categories = models.BooleanField(
        default=True,
        verbose_name=_('Display categories'),
    )

    display_tags = models.BooleanField(
        default=True,
        verbose_name=_('Display tags'),
    )

    display_popular_entries = models.BooleanField(
        default=True,
        verbose_name=_('Display popular entries'),
    )

    display_last_entries = models.BooleanField(
        default=True,
        verbose_name=_('Display last entries'),
    )

    display_archive = models.BooleanField(
        default=True,
        verbose_name=_('Display archive'),
    )

    disqus_api_secret = models.TextField(
        blank=True
    )

    disqus_shortname = models.CharField(
        max_length=128,
        blank=True,
    )

    num_entries_page = models.IntegerField(
        default=5,
        verbose_name=_('Entries per page'),
    )

    num_last_entries = models.IntegerField(
        default=3,
        verbose_name=_('Last entries limit'),
    )

    num_popular_entries = models.IntegerField(
        default=3,
        verbose_name=_('Popular entries limit'),
    )

    num_tags_entry_header = models.IntegerField(
        default=5,
        verbose_name=_('Tags limit entry header'),
    )

    content_panels = Page.content_panels + [

        FieldPanel('description', classname="full"),
        ImageChooserPanel('header_image'),

        MultiFieldPanel([
            InlinePanel('blog_projects', label=_("Projects")),
            InlinePanel('blog_speeches', label=_("Speeches")),
        ], heading=_("Portfolio")),
    ]

    settings_panels = Page.settings_panels + [
        FieldPanel('owner', classname="full"),
        MultiFieldPanel([
            FieldPanel('display_categories'),
            FieldPanel('display_tags'),
            FieldPanel('display_popular_entries'),
            FieldPanel('display_last_entries'),
            FieldPanel('display_archive'),
        ], heading=_("Widgets")),
        MultiFieldPanel([
            FieldPanel('num_entries_page'),
            FieldPanel('num_last_entries'),
            FieldPanel('num_popular_entries'),
            FieldPanel('num_tags_entry_header'),
        ], heading=_("Parameters")),
        MultiFieldPanel([
            FieldPanel('display_comments'),
            FieldPanel('disqus_api_secret'),
            FieldPanel('disqus_shortname'),
        ], heading=_("Comments")),
    ]

    subpage_types = ['blog.EntryPage']

    def get_entries(self):
        field_name = 'owner__%s' % getattr(settings, 'PUPUT_USERNAME_FIELD', 'username')
        return EntryPage.objects.descendant_of(self).live().order_by('-date').select_related('owner')


    def get_context(self, request, *args, **kwargs):
        context = super(BlogPage, self).get_context(request, *args, **kwargs)
        context['entries'] = self.entries
        context['blog_page'] = self
        context['search_type'] = getattr(self, 'search_type', "")
        context['search_term'] = getattr(self, 'search_term', "")
        return context

    class Meta:
        verbose_name = _('Blog')


@register_snippet
class Category(models.Model):
    name = models.CharField(
        max_length=80,
        unique=True,
        verbose_name=_('Category name'),
    )

    icon = models.ForeignKey(
        'wagtailimages.Image',
        verbose_name=_('Icon'),
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    slug = models.SlugField(
        unique=True,
        max_length=80,
    )

    parent = models.ForeignKey(
        'self',
        blank=True,
        null=True, related_name="children",
        verbose_name=_('Parent category'),
    )

    description = models.CharField(
        max_length=500,
        blank=True,
        verbose_name=_('Description'),
    )

    objects = CategoryManager()

    panels = [
        MultiFieldPanel(
            [
                FieldPanel('name'),
                FieldPanel('slug'),
                ImageChooserPanel('icon'),
                SnippetChooserPanel('parent'),
                FieldPanel('description', classname="full"),
            ],
            heading=_("Category"),
        )
    ]

    def __str__(self):
        return self.name

    def clean(self):
        if self.parent:
            parent = self.parent
            if self.parent == self:
                raise ValidationError(_('Parent category cannot be self.'))
            if parent.parent and parent.parent == self:
                raise ValidationError(_('Cannot have circular Parents.'))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


@register_snippet
class Project(models.Model):
    name = models.CharField(
        max_length=80,
        unique=True,
        verbose_name=_('Project name'),
    )

    link = models.URLField(
        unique=True,
    )

    description = models.CharField(
        max_length=500,
        blank=True,
        verbose_name=_('Description'),
    )

    thumb = models.ForeignKey(
        'wagtailimages.Image',
        verbose_name=_('Thumb'),
        help_text=_("Small image to previsualization 350 x 350"),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    image = models.ForeignKey(
        'wagtailimages.Image',
        verbose_name=_('Image'),
        help_text=_("Full visualization image"),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    panels = [
        MultiFieldPanel(
            [
                FieldPanel('name'),
                FieldPanel('description', classname="full"),
                FieldPanel('link'),
            ],
            heading=_("Info"),
        ),
        MultiFieldPanel(
            [
                ImageChooserPanel('thumb'),
                ImageChooserPanel('image'),
            ],
            heading=_("Images"),
        )
    ]


    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _("Project")
        verbose_name_plural = _("Projects")


@register_snippet
class Speech(models.Model):
    title = models.CharField(
        max_length=140,
        unique=True,
        verbose_name=_('Speech title'),
    )

    community = models.CharField(
        max_length=140,
        unique=True,
        verbose_name=_('Community'),
    )

    link = models.URLField(
        verbose_name=_('Link to slides'),
        unique=True,
    )

    description = models.CharField(
        max_length=500,
        blank=True,
        verbose_name=_('Description'),
    )

    thumb = models.ForeignKey(
        'wagtailimages.Image',
        verbose_name=_('Thumb'),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    image = models.ForeignKey(
        'wagtailimages.Image',
        verbose_name=_('Image'),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    panels = [
        MultiFieldPanel(
            [
                FieldPanel('title', classname="title"),
                FieldPanel('description', classname="full"),
                FieldPanel('community'),
                FieldPanel('link'),
            ],
            heading=_("Info"),
        ),
        MultiFieldPanel(
            [
                ImageChooserPanel('thumb'),
                ImageChooserPanel('image'),
            ],
            heading=_("Images"),
        )
    ]

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = _("Speech")
        verbose_name_plural = _("Speeches")


class CategoryEntryPage(models.Model):
    category = models.ForeignKey(
        'Category',
        related_name="+",
        verbose_name=_('Category'),
    )

    page = ParentalKey(
        'EntryPage',
        related_name='entry_categories',
    )

    panels = [

apps/templates/blog/base.html
{% load static i18n wagtailcore_tags wagtailroutablepage_tags wagtailuserbar compress blog_tags %}
{% wagtailuserbar %}
<!DOCTYPE HTML>
<html>
    <head>
        <title>
            {% block title %}
                {{ blog_page.title }}
                    {% if blog_page.description %} | {{ blog_page.description }}{% endif %}
            {% endblock title %}
        </title>
        <meta name="title" content="{% block meta_title %}{% if blog_page.seo_title %}{{ blog_page.seo_title }}{% else %}{{ blog_page.title }}{% endif %}{% endblock meta_title %}"/>
        <meta name="description" content="{% block meta_description %}{{ blog_page.search_description }}{% endblock meta_description %}"/>
        <link rel="canonical" href="{% block canonical %}{% canonical_url %}{% endblock canonical %}"/>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {% include 'blog/partials/favicon.html' %}

        <!--[if lte IE 8]><script src="{% static 'js/ie/html5shiv.js' %}"></script><![endif]-->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" href="{% static 'css/monokai.css' %}" />
        <!--[if lte IE 8]><link rel="stylesheet" href=" {% static 'css/ie8.css' %}" /><![endif]-->
    </head>
    <body>

        <!-- Header -->
        {% block menu %}
            {% include 'blog/partials/header.html' with blog=blog_page active="feed"%}
        {% endblock %}


        <!-- Wrapper -->
            <div id="wrapper">

                <!-- Main -->
                    <div id="main">
                        {% block content %}

                        {% endblock %}

                    </div>

                <!-- Footer -->
                {%  include 'blog/partials/footer.html' %}
            </div>

        {% include 'blog/partials/analitycs.html' %}
        <!-- Scripts -->
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/jssocials.js' %}"></script>
        <script src="{% static 'js/owl.carousel.js' %}"></script>
        <script src="{% static 'js/skel.min.js' %}"></script>
        <script src="{% static 'js/util.js' %}"></script>
        <!--[if lte IE 8]><script src="{% static 'js/ie/respond.min.js' %}"></script><![endif]-->
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/start.js' %}"></script>

    </body>
</html>

apps/templates/blog/blog_page.html
{% extends "blog/base.html" %}

{% load static i18n wagtailcore_tags wagtailimages_tags blog_tags %}

{% block title %}
    {% if search_term %}
        {{ search_term }} | {{ blog_page.title }}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock title %}

{% block menu %}
    {% include 'blog/partials/header.html' with blog=blog_page active="posts"%}
{% endblock %}

{% block content %}
    <div class="header-image">
        <img src="{% static 'img/code.jpg' %}">
    </div>

    {% include 'blog/partials/posts.html' with blog=blog_page %}

    {% categories_list %}
{% endblock %}

apps/templates/blog/contact_page.html
{% extends "blog/base.html" %}

{% load static i18n wagtailcore_tags wagtailimages_tags blog_tags %}

{% block title %}
    {% if search_term %}
        {{ search_term }} | {{ blog_page.title }}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock title %}

{% block menu %}
    {% include 'blog/partials/header.html' with blog=blog_page active="contact"%}
{% endblock %}

{% block content %}
    <div class="header-image">
        <img src="{% static 'img/code.jpg' %}">
    </div>
    <section id="four">
        <div class="container">
            <h3>{% trans 'Contáctame' %}</h3>
            <p>{% trans 'Hola! Mi nombre es Victor, Vic para los amigos, Soy un desarrollador fullstack y entusiasta de la tecnología, si hay algo en que te pueda ayudar, escríbeme.' %}</p>
            <form method="post" action="">
                {% csrf_token %}
                <div class="row uniform ">

                    <div class="6u 12u(xsmall)">
                        <input type="text" name="name" id="id_name" placeholder="{% trans 'Nombre' %}" class="form-field {% if form.name.errors %}error{% endif %}"/>
                        {{ form.name.errors }}
                    </div>
                    <div class="6u 12u(xsmall)">
                        <input type="email" name="email" id="id_email" placeholder="{% trans 'Correo' %}" class="form-field {% if form.name.errors %}error{% endif %}"/>
                        {{ form.name.errors }}
                    </div>
                </div>
                <div class="row uniform">
                    <div class="12u">
                        <input type="text" name="subject" id="id_subject" placeholder="{% trans 'Asunto' %}" class="form-field {% if form.name.errors %}error{% endif %}"/>
                        {{ form.name.errors }}
                    </div>
                </div>
                <div class="row uniform">
                    <div class="12u">
                        <textarea name="message" id="id_message" placeholder="{% trans 'Mensaje' %}" rows="6" class="form-field {% if form.name.errors %}error{% endif %}"></textarea>
                        {{ form.name.errors }}
                    </div>
                </div>
                <div class="row uniform">
                    <div class="12u">
                        <ul class="actions">
                            <li><input type="submit" class="button special" value="{% trans 'Enviar Mensaje' %}" /></li>
                            <li><input type="reset" value="{% trans 'Borrar' %}" /></li>
                        </ul>
                    </div>
                </div>
            </form>


            <br>
            <hr>
            <br><br>

{#            <form action="" method="post">{% csrf_token %}#}
{#                {{ form.as_p }}#}
{#                <input type="submit" value="Send message" />#}
{#            </form>#}
        </div>
    </section>
{% endblock %}

apps/templates/blog/contact_thanks.html
{% extends "blog/base.html" %}

{% load static i18n wagtailcore_tags wagtailimages_tags blog_tags %}

{% block title %}
    {% if search_term %}
        {{ search_term }} | {{ blog_page.title }}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock title %}

{% block menu %}
    {% include 'blog/partials/header.html' with blog=blog_page active="contact"%}
{% endblock %}

{% block content %}
    <div class="header-image">
        <img src="{% static 'img/code.jpg' %}">
    </div>
    <section id="four">
        <div class="container">
            <h3>{% trans 'Gracias! :)' %}</h3>
            <p>
                {% trans 'Gracias por el mensaje, Trataré de responderte lo antes posible.' %}
                <br><br>
                <a href="{% url 'blog:contact_page' %}" class="button special">{% trans 'Enviar otro mensaje' %}</a>
                <a href="/" class="button">{% trans 'Regresar al Inicio' %}</a>
            </p>
            <br><br><br><br><br>

        </div>
    </section>
{% endblock %}

apps/templates/blog/entry_page.html
{% extends "blog/base.html" %}
{% load static i18n wagtailcore_tags wagtailimages_tags blog_tags %}

{% block title %}
    {% if search_term %}
        {{ search_term }} | {{ blog_page.title }}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock title %}

{% block menu %}
    {% include 'blog/partials/header.html' with blog=blog_page active="posts"%}
{% endblock %}

{% block content %}

    <div class="header-image">
        {% if self.header_image and self.show_header %}
            {% image self.header_image fill-900x220 as header_image %}
            <img alt="{{ self.header_image.title }}" src="{{ header_image.url }}">
        {% else %}
            <img src="{% static 'img/code.jpg' %}">
        {% endif %}
    </div>


    <div class="container detail">

        <header>

            {% include "blog/partials/author.html" with entry=self mode='detail' %}

            <h2 class="title">
                {{ self.title }}
            </h2>
            <span class="date"><i class="fa fa-calendar"></i>&nbsp;&nbsp;{{ self.date|date:"DATE_FORMAT" }} </span>

        </header>

        <article>
            {% for block in page.body %}
                <section>{% include_block block %}</section>
            {% endfor %}
        </article>

        <div class="groups">
            {% if self.tags.count > 0 %}
                {% tags_list blog_page.num_tags_entry_header entry.tags %}
            {% endif %}
            <div style="clear: both"><br></div>
        </div>

        {% show_comments %}
        <br><br>
    </div>

{% endblock %}

apps/templates/blog/portfolio_page.html
{% extends "blog/base.html" %}

{% load static i18n wagtailcore_tags wagtailimages_tags blog_tags %}

{% block title %}
    {% if search_term %}
        {{ search_term }} | {{ blog_page.title }}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock title %}

{% block menu %}
    {% include 'blog/partials/header.html' with blog=blog_page active="about"%}
{% endblock %}

{% block content %}
    <div class="header-image">
        <img src="{% static 'img/code.jpg' %}">
    </div>
    <section>
        <div class="container">
            <h3 class="title">{% trans 'Acerca de mí' %}</h3>
            <p>
                {% trans 'Hola! mi nombre es Victor Aguilar @jvacx, soy desarrollador web y móvil con tres años de experiencia me encanta la tecnología, crear y experimentar son de las cosas que mas disfruto.' %}
            </p>

            <h3 class="title">{% trans 'Proyectos' %}</h3>
            <p>
                {% trans 'A lo largo de estos años tuve la fortuna de liderar y participar en varios proyectos interesantes, aqui algunos de ellos.' %}
            </p>
            {% project_list %}
            <br>
            <h3 class="title">{% trans 'Comunidades' %}</h3>

            <p>
                {% trans 'Soy firme creyente de que la única manera de aportar un valor real es compartiendo lo aprendido y que mejor forma de hacerlo que a traves de las comunidades de tecnología.' %}
            </p>

            {% speech_list %}

        </div>
    </section>

{% endblock %}