config/urls.py
# -*- encoding:utf-8 -*-

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from apps.contrib.views import LandingView

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls


urlpatterns = [

    # Django ADMIN
    url(settings.ADMIN_URL, admin.site.urls),

    # Blog Admin
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^offline/$', TemplateView.as_view(template_name='offline.html')),

    # Blog Pages
    url(r'', include('apps.blog.urls', namespace='blog')),
    url(r'', include(wagtail_urls)),

    # Platform VIEWS and ENDPOINTS
    url(r'', include('apps.users.urls', namespace='users')),
    url(r'', include('apps.credentials.urls', namespace="credentials")),

    # Third parts
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^docs/', include('rest_framework_swagger.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:

    urlpatterns += [
        url(
            regex=r'^test/login/?$',
            view=TemplateView.as_view(template_name='test/login.html')
        ),
    ]

    # Test Email templates
    urlpatterns += [
        url(
            regex=r'^email/base/?$',
            view=TemplateView.as_view(template_name='layouts/base_email.html')
        ),

        url(
            regex=r'^email/web/confirmation/?$',
            view=TemplateView.as_view(template_name='account/email/email_confirmation_message.html')
        ),

        url(
            regex=r'^email/web/signup/?$',
            view=TemplateView.as_view(template_name='account/email/email_confirmation_signup_message.html')
        ),

        url(
            regex=r'^email/web/password-reset/?$',
            view=TemplateView.as_view(template_name='account/email/password_reset_key_message.html')
        ),

        url(
            regex=r'^email/mobile/welcome/?$',
            view=TemplateView.as_view(template_name='credentials/email/account_welcome_message.html')
        ),
    ]

    # Test error pages
    urlpatterns += [
        url(r'^400/$', TemplateView.as_view(template_name='errors/400.html')),
        url(r'^403/$', TemplateView.as_view(template_name='errors/403.html')),
        url(r'^404/$', TemplateView.as_view(template_name='errors/404.html')),
        url(r'^500/$', TemplateView.as_view(template_name='errors/500.html')),
    ]

    urlpatterns += [
        url(r'^error/400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^error/403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^error/404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^error/500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
else:
    handler400 = TemplateView.as_view(template_name="errors/400.html")
    handler403 = TemplateView.as_view(template_name="errors/403.html")
    handler404 = TemplateView.as_view(template_name="errors/404.html")
    handler500 = TemplateView.as_view(template_name="errors/500.html")

apps/users/urls/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from apps.users.transactions import change_email, cancel_account
from apps.users.views import (
    DashboardView, ProfileView, SettingsView,
    UserDetailView, UserUpdateView, ProfileSessionsView,
)

urlpatterns = [

    # Regular Views
    url(
        regex=r'^dashboard/$',
        view=DashboardView.as_view(),
        name='view-dashboard'
    ),

    url(
        regex=r'^profile/$',
        view=ProfileView.as_view(),
        name='view-profile'
    ),

    url(
        regex=r'^settings/$',
        view=SettingsView.as_view(),
        name='view-settings'
    ),

    url(
        regex=r'^account/(?P<username>[\w.@+-]+)/$',
        view=UserDetailView.as_view(),
        name='view-detail'
    ),

    url(
        regex=r'^account/update/$',
        view=UserUpdateView.as_view(),
        name='view-update'
    ),

    url(
        regex=r'^account/change-email/(?P<token>.*)/$',
        view=change_email,
        name="view-change-email",
    ),

    url(
        regex=r'^account/cancel-account/(?P<token>.*)/$',
        view=cancel_account,
        name="view-cancel-account",
    ),

    url(
        regex=r'^profile/sessions/$',
        view=ProfileSessionsView.as_view(),
        name='view-profile-sessions'
    ),
]

apps/templates/partials/navigation/horizontal-boxed.html
<div class="app-navigation-horizontal margin-bottom-15">    
    <div class="container container-boxed">
        <nav>
            <ul>
                <li class="active">
                    <a href="index.html"><span class="icon-laptop-phone"></span> Dashboard</a>
                    <ul>
                        <li class="active"><a href="#">Statistics</a></li>
                        <li><a href="#">Visitors</a></li>
                        <li><a href="#">Sales</a></li>
                        <li><a href="#">Customers</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><span class="icon-archive2"></span> Navigation Item 1</a>                
                    <ul>
                        <li><a href="#">Sub Element 1-1</a></li>
                        <li><a href="#">Sub Element 1-2</a></li>
                        <li><a href="#">Sub Element 1-3</a></li>
                        <li><a href="#">Sub Element 1-4</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><span class="icon-user-plus"></span> Another Item 2</a>                
                    <ul>
                        <li><a href="#">Another Sub 2-1</a></li>
                        <li><a href="#">Another Sub 2-2</a></li>
                        <li><a href="#">Another Sub 2-3</a></li>
                        <li><a href="#">Another Sub 2-4</a></li>
                        <li><a href="#">Another Sub 2-5</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><span class="icon-calendar-full"></span> Perfect Item 3</a>                
                    <ul>
                        <li><a href="#">Perfect Sub 3-1</a></li>
                        <li><a href="#">Perfect Sub 3-2</a></li>
                        <li><a href="#">Perfect Sub 3-3</a></li>
                        <li><a href="#">Perfect Sub 3-4</a></li>
                        <li><a href="#">Perfect Sub 3-5</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

apps/templates/partials/navigation/horizontal.html
<div class="app-navigation-horizontal">
    <nav>
        <ul>
            <li class="active">
                <a href="index.html"><span class="icon-laptop-phone"></span> Dashboard</a>
                <ul>
                    <li class="active"><a href="#">Statistics</a></li>
                    <li><a href="#">Visitors</a></li>
                    <li><a href="#">Sales</a></li>
                    <li><a href="#">Customers</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><span class="icon-archive2"></span> Navigation Item 1</a>                
                <ul>
                    <li><a href="#">Sub Element 1-1</a></li>
                    <li><a href="#">Sub Element 1-2</a></li>
                    <li><a href="#">Sub Element 1-3</a></li>
                    <li><a href="#">Sub Element 1-4</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><span class="icon-user-plus"></span> Another Item 2</a>                
                <ul>
                    <li><a href="#">Another Sub 2-1</a></li>
                    <li><a href="#">Another Sub 2-2</a></li>
                    <li><a href="#">Another Sub 2-3</a></li>
                    <li><a href="#">Another Sub 2-4</a></li>
                    <li><a href="#">Another Sub 2-5</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><span class="icon-calendar-full"></span> Perfect Item 3</a>                
                <ul>
                    <li><a href="#">Perfect Sub 3-1</a></li>
                    <li><a href="#">Perfect Sub 3-2</a></li>
                    <li><a href="#">Perfect Sub 3-3</a></li>
                    <li><a href="#">Perfect Sub 3-4</a></li>
                    <li><a href="#">Perfect Sub 3-5</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</div>

apps/templates/partials/navigation/mobile.html
<div class="app-navigation-mobile">
    <ul>
        <li><a href="index.html"><span class="nav-icon-hexa">Hm</span> Home</a></li>
        <li><a href="#"><span class="nav-icon-hexa">Au</span> About Us</a></li>
        <li><a href="#"><span class="nav-icon-hexa">Pf</span> Portfolio</a></li>
        <li><a href="#"><span class="nav-icon-hexa">Ct</span> Contacts</a></li>
        <li><a href="#"><span class="nav-icon-hexa">Sp</span> Support</a></li>
        <li><a href="#"><span class="nav-icon-hexa">Su</span> Sign Up</a></li>
    </ul>
</div>

apps/templates/partials/navigation/navigation-list.html
{% load i18n static %}
<nav>
    <ul>
        <li class="title">{% trans 'ADMINISTRACÍON' %}</li>
        <li>
            <a class="{% if menu == "dashboard" %}active{% endif %}"
            href="{% url 'users:view-dashboard' %}">
                <span class="fa fa-bar-chart-o"></span>
                {% trans 'PANEL' %}
            </a>
        </li>
        <li>
            <a class="{% if menu == "settings" %}active{% endif %}"
            href="{% url 'users:view-settings' %}">
                <span class="fa fa-cogs"></span>
                {% trans 'AJUSTES' %}
            </a>
        </li>

    </ul>
</nav>